---
driver:
  name: vagrant

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.7
    run_list:
    - recipe[yum]

# default values: https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/provisioner/chef_base.rb#L183-L190
provisioner:
  name: chef_zero
  require_chef_omnibus: true

suites:
  - name: default
    run_list:
      - recipe[rackspacecloud_test]
